# Generated by Django 2.0.6 on 2019-03-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCRUDApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellmodel',
            name='pic',
            field=models.CharField(default='URL', max_length=300),
        ),
    ]
