# Generated by Django 2.0.6 on 2019-03-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCRUDApp', '0002_sellmodel_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9999999),
        ),
    ]
